apiVersion: v1
kind: Pod
metadata:
  name: full
  labels:
    app: full
spec:
  containers:
    - name: myback
      image: back
      ports:
        - containerPort: 3000
    - name: front
      image: front
      ports:
        - containerPort: 80
