apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
    - image: back
      context: ./back
    - image: front
      context: ./front
    - image: db
      context: ./db
    - image: db-manager
      context: ./db_manager
deploy:
  kubectl:
    manifests:
      - k8s-*
