FROM node:current-alpine as builder

COPY package.json yarn.lock ./
RUN yarn

COPY . ./
RUN yarn build

FROM nginx:1.12-alpine
COPY --from=builder /build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
